apiVersion: v1
kind: Service
metadata:
  name: {{include "aptly.fullname" .}}-nginx
  labels: {{- include "aptly.labelsNginx" . | nindent 4}}
spec:
  type: {{.Values.service.type}}
  ports:
    - port: {{.Values.service.port}}
      targetPort: http
      protocol: TCP
      name: http
  selector: {{- include "aptly.selectorLabelsNginx" . | nindent 4}}
