apiVersion: v2
name: aptly
description: Deploy aptly securely to a Kubernetes cluster
type: application
version: 0.1.0
appVersion: "1.15.0"
maintainers:
  - name: Synthread Labs
    email: contact@synthread.net
    url: https://synthread.net/
